Repository Chris-Johnston/PGTRTKD3000DGOTY, pull requests merged in 2018-12, with the labels that each got.

#40 Add error landing pages
  PetGame/PetGame.csproj
  PetGame/Startup.cs
  PetGame/web.config
  PetGame/wwwroot/placeholder.html
Labels: API, Front-end, Small

#39 Implement Pet Controller API Endpoints
  .gitignore
  PetGame.Core/Models/Pet.cs
  PetGame.Tests/PetTests.cs
  PetGame/Controllers/PetController.cs
  PetGame/Gulpfile.js
  PetGame/Pages/Index.cshtml
  PetGame/Pages/PetTester.cshtml
  PetGame/Pages/PetTester.cshtml.cs
  PetGame/Pages/_Layout.cshtml
  PetGame/PetGame.csproj
  PetGame/Services/PetService.cs
  PetGame/Startup.cs
  PetGame/gulpfile.js
  PetGame/package-lock.json
  PetGame/package.json
  PetGame/scripts/petDebugger.ts
  PetGame/scripts/tsconfig.json
  PetGame/style/main.less
  PetGame/web.config
  README.md
Labels: API

#42 Implement the RaceController and RaceService
  PetGame/Controllers/RaceController.cs
  PetGame/Services/RaceService.cs
Labels: API

#51 Fix #45 Fix null reference thrown when logging in/registering
  PetGame/Controllers/LoginController.cs
Labels: bug

#41 Implement Leaderboard API Endpoint
  PetGame.Core/Models/LeaderboardEntry.cs
  PetGame/Controllers/LeaderboardController.cs
  PetGame/Models/LeaderboardRequestModel.cs
  PetGame/Pages/Index.cshtml
  PetGame/PetGame.csproj
  PetGame/Services/LeaderboardService.cs
Labels: API

#56 Create the "Add Pet" page
  PetGame.Core/Models/Pet.cs
  PetGame/Controllers/UserController.cs
  PetGame/Models/CreatePetModel.cs
  PetGame/Pages/AddPet.cshtml
  PetGame/Pages/AddPet.cshtml.cs
  PetGame/Pages/Index.cshtml
  PetGame/style/main.less
  PetGame/wwwroot/img/pets/mysterypet.png
Labels: API, Front-end

#54 Fix #48 Add Phone Number column to User table
  PetGame.Core/Models/User.cs
  PetGame.Tests/UserTests.cs
  PetGame.sln
  PetGame/Services/LoginService.cs
  SQL/Migrations/01_Alter_Table_User_PhoneNumber.sql
Labels: API, DB

#58 Define more of the ActivityTypes
  PetGame.Core/Enum/ActivityType.cs
  PetGame.sln
  SQL/Migrations/02_DropCreate_Table_Activity_NewActivityType.sql
Labels: API, Breaking, DB

#61 Add Pet Images
  PetGame.Core/Models/Pet.cs
  PetGame.sln
  PetGame/Controllers/ImageController.cs
  PetGame/Controllers/UserController.cs
  PetGame/Models/CreatePetModel.cs
  PetGame/Pages/AddPet.cshtml
  PetGame/Pages/AddPet.cshtml.cs
  PetGame/Pages/Index.cshtml
  PetGame/Pages/Index.cshtml.cs
  PetGame/PetImages.cs
  PetGame/Services/PetService.cs
  PetGame/style/main.less
  PetGame/wwwroot/img/pets/pet_01.png
  PetGame/wwwroot/img/pets/pet_01.psd
  PetGame/wwwroot/img/pets/pet_02.png
  PetGame/wwwroot/img/pets/pet_02.psd
  PetGame/wwwroot/img/pets/pet_03.png
  PetGame/wwwroot/img/pets/pet_04.png
  PetGame/wwwroot/img/pets/pet_05.png
  PetGame/wwwroot/img/pets/pet_06.png
  PetGame/wwwroot/img/pets/pet_06.psd
  PetGame/wwwroot/img/pets/pet_07.png
  PetGame/wwwroot/img/pets/pet_08.png
  PetGame/wwwroot/img/pets/pet_08.psd
  PetGame/wwwroot/img/pets/pet_09.png
  PetGame/wwwroot/img/pets/pet_10.png
  PetGame/wwwroot/img/pets/pet_10.psd
  SQL/Migrations/03_Alter_Table_Pet_Image.sql
Labels: API, Front-end

#63 Update the leaderboard to have pet images
  PetGame.Core/Models/LeaderboardEntry.cs
  PetGame/Pages/Leaderboard.cshtml
  PetGame/Services/LeaderboardService.cs
  PetGame/style/main.less
Labels: API, Front-end, Small

#65 Add Favicons and Logo Files
  PetGame/Pages/Index.cshtml
  PetGame/Pages/_Layout.cshtml
  PetGame/style/main.less
  PetGame/wwwroot/android-chrome-192x192.png
  PetGame/wwwroot/android-chrome-384x384.png
  PetGame/wwwroot/apple-touch-icon.png
  PetGame/wwwroot/browserconfig.xml
  PetGame/wwwroot/favicon-16x16.png
  PetGame/wwwroot/favicon-32x32.png
  PetGame/wwwroot/favicon.ico
  PetGame/wwwroot/img/logo_full.png
  PetGame/wwwroot/img/logo_small.png
  PetGame/wwwroot/mstile-150x150.png
  PetGame/wwwroot/safari-pinned-tab.svg
  PetGame/wwwroot/site.webmanifest
Labels: Front-end, Small, enhancement

#57 Implement Status API Endpoint in Pet and User
  PetGame.Core/Models/PetStatus.cs
  PetGame/Controllers/PetController.cs
  PetGame/Controllers/UserController.cs
  PetGame/Services/ActivityService.cs
  PetGame/Services/PetService.cs
Labels: API

#68 Change how TimeOfNextAction is calculated
  PetGame.Core/Models/PetStatus.cs
  PetGame/Services/PetService.cs
Labels: API, Needs Review, bug

#67 Integrate Pet Status API into pages, add interactivity to pet status page
  PetGame/Controllers/PetController.cs
  PetGame/Pages/Index.cshtml
  PetGame/Pages/Index.cshtml.cs
  PetGame/Pages/Pet.cshtml
  PetGame/Pages/Pet.cshtml.cs
  PetGame/Pages/_Layout.cshtml
  PetGame/PetGame.csproj
  PetGame/Services/ActivityService.cs
  PetGame/Services/PetService.cs
  PetGame/package-lock.json
  PetGame/package.json
  PetGame/scripts/pet.ts
  PetGame/scripts/petDebugger.ts
  PetGame/scripts/petStatus.ts
  PetGame/scripts/tsconfig.json
  PetGame/style/main.less
Labels: API, Front-end

#62 Send confirmation notification + Discord webhook support
  PetGame/Controllers/LoginController.cs
  PetGame/Services/LoginService.cs
  PetGame/Services/NotificationService.cs
  PetGame/Services/TwilioService.cs
  PetGame/Startup.cs
  README.md
Labels: API

#71 Various Bug Fixes
  PetGame.Core/Models/Pet.cs
  PetGame/Controllers/LoginController.cs
  PetGame/Controllers/PetController.cs
  PetGame/Controllers/RaceController.cs
  PetGame/Pages/AddPet.cshtml
  PetGame/Pages/Login.cshtml
  PetGame/Pages/Login.cshtml.cs
  PetGame/Pages/Pet.cshtml
  PetGame/Pages/Pet.cshtml.cs
  PetGame/Pages/Race.cshtml
  PetGame/Pages/Race.cshtml.cs
  appveyor.yml
Labels: API, Front-end
