Repository Chris-Johnston/PGTRTKD3000DGOTY, pull requests merged in 2018-11, with the labels that each got.

#4 Add the User table create script
  PetGame.sln
  SQL/Create_Table_User.sql
Labels: DB

#2 Created sql script for creating the Race Table
  PetGame.Core/Models/Race.cs
  PetGame.sln
  PetGame/PetGame.csproj
  SQL/Create_Race_DummyData.sql
  SQL/Create_Race_Table.sql
Labels: DB

#6 added CREATE TABLE PetActivity
  PetGame.Core/Models/Activity.cs
  PetGame.sln
  SQL/Create_Table_Activity.sql
Labels: DB

#5 Add the script for creating the usertoken table
  PetGame.Core/Models/UserToken.cs
  PetGame.sln
  SQL/Create_Table_UserToken.sql
Labels: DB

#3 Add the Pet table create script
  PetGame.sln
  SQL/Create_Table_Pet.sql
Labels: DB

#7 Add race sampledata
  PetGame.sln
  SQL/Create_PlaceholderData_Race.sql
  SQL/Create_Table_Pet.sql
  SQL/Insert_PlaceholderData_Race.sql
Labels: DB

#11 Created 10 sample Pet insert statements
  PetGame.sln
  SQL/Create_Table_Pet.sql
  SQL/Insert_PlaceholderData_Pet.sql
Labels: DB

#9 added data for activity
  PetGame.sln
  SQL/Insert_PlaceholderData_Activity.sql
Labels: DB

#8 Add user usertoken sampledata
  PetGame.sln
  SQL/Create_Table_User.sql
  SQL/Insert_PlaceholderData_User.sql
  SQL/Insert_PlaceholderData_UserToken.sql
Labels: DB

#14 Add SQL Table Create and Sample Data Scripts
  PetGame.Core/Models/Activity.cs
  PetGame.Core/Models/Race.cs
  PetGame.Core/Models/UserToken.cs
  PetGame.sln
  PetGame/PetGame.csproj
  SQL/Create_Table_Activity.sql
  SQL/Create_Table_All.sql
  SQL/Create_Table_Pet.sql
  SQL/Create_Table_Race.sql
  SQL/Create_Table_User.sql
  SQL/Create_Table_UserToken.sql
  SQL/Insert_PlaceholderData_Activity.sql
  SQL/Insert_PlaceholderData_Pet.sql
  SQL/Insert_PlaceholderData_Race.sql
  SQL/Insert_PlaceholderData_User.sql
  SQL/Insert_PlaceholderData_UserToken.sql
  SQL/Insert_SampleData_All.sql
Labels: DB

#36 Add regex validation
  PetGame.Core/Exception/InsecurePasswordException.cs
  PetGame.Core/Models/Pet.cs
  PetGame.Core/Models/User.cs
  PetGame.Core/Util/Cryptography.cs
  PetGame.Tests/CryptographyTests.cs
  PetGame.Tests/PetTests.cs
  PetGame.Tests/UserTests.cs
Labels: API, Small, Testing

#35 Cleanup some CI Warnings
  PetGame.Core/Exception/InsecurePasswordException.cs
  PetGame.Core/Util/CryptographyUtil.cs
  PetGame.Tests/CryptographyTests.cs
  PetGame/Controllers/LoginController.cs
  PetGame/GlobalSuppressions.cs
  PetGame/Services/LoginService.cs
Labels: API, Breaking, Small

#34 Fix #32 Implement Page Templates + Add Bootstrap CSS
  PetGame/Models/UserLoginModel.cs
  PetGame/Pages/Index.cshtml
  PetGame/Pages/Index.cshtml.cs
  PetGame/Pages/Login.cshtml
  PetGame/Pages/Login.cshtml.cs
  PetGame/Pages/_Layout.cshtml
  PetGame/PetGame.csproj
  PetGame/Services/LoginService.cs
  PetGame/wwwroot/index.html
  PetGame/wwwroot/login.html
Labels: Breaking, Front-end
